# docker-compose.test.yml (Versión Simplificada con Script Init)
version: '3.8'

services:
  db_test:
    image: mysql:8.0
    container_name: recetas_db_test
    # Variables para crear usuario/db base Y CONTRASEÑA ROOT
    environment:
      MYSQL_ROOT_PASSWORD: testrootpassword # Necesaria para que el script init pueda correr como root implícitamente
      MYSQL_DATABASE: recetas_test_db
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "3307:3306"
    volumes:
      # Montar el script de inicialización robusto
      - ./scripts/mysql/init-test-db.sql:/docker-entrypoint-initdb.d/init-test-db.sql
    # Comentar o eliminar volumen de datos persistentes
    # - db_test_data:/var/lib/mysql
    healthcheck:
      # Healthcheck puede seguir usando testuser, debería funcionar DESPUÉS de que el script init corra
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "testuser", "-ptestpassword"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s # Dar tiempo a que el script init se ejecute

# volumes:
#   db_test_data: